export const NEW_MESSAGE = 'NEW_MESSAGE';
export const USER_TYPING = 'USER_TYPING';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_CLOSED = 'SOCKET_CLOSED';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_USERS = 'ADD_USERS';
