export const NEW_MESSAGE = 'NEW_MESSAGE';
export const USER_TYPING = 'USER_TYPING';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_CLOSED = 'SOCKET_CLOSED';

export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
